// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

import { implicitReturnType } from '../base/types.js';
import { Exchange as _Exchange } from '../base/Exchange.js';

interface Exchange {
    publicGetAssets (params?: {}): Promise<implicitReturnType>;
    publicGetPairs (params?: {}): Promise<implicitReturnType>;
    publicGetPairsPairOrderbook (params?: {}): Promise<implicitReturnType>;
    publicGetTime (params?: {}): Promise<implicitReturnType>;
    privateGetCustomer (params?: {}): Promise<implicitReturnType>;
    privateGetCustomerApiKeyStatus (params?: {}): Promise<implicitReturnType>;
    privateGetOrders (params?: {}): Promise<implicitReturnType>;
    privateGetTrades (params?: {}): Promise<implicitReturnType>;
    privateGetOrdersByVenueOrderIdId (params?: {}): Promise<implicitReturnType>;
    privateGetOrdersByCustomerObjectIdId (params?: {}): Promise<implicitReturnType>;
    privatePostOrders (params?: {}): Promise<implicitReturnType>;
    privateDeleteOrders (params?: {}): Promise<implicitReturnType>;
    privateDeleteOrdersByVenueOrderIdId (params?: {}): Promise<implicitReturnType>;
    privateDeleteOrdersByCustomerObjectIdId (params?: {}): Promise<implicitReturnType>;
    dwnonce?: number;
}
abstract class Exchange extends _Exchange {}

export default Exchange