// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

import { implicitReturnType } from '../base/types.js';
import { Exchange as _Exchange } from '../base/Exchange.js';

interface Exchange {
    publicGetPublicGetSymbolsReference (params?: {}): Promise<implicitReturnType>;
    publicGetPublicGetBook (params?: {}): Promise<implicitReturnType>;
    privatePostPrivatePlaceOrder (params?: {}): Promise<implicitReturnType>;
    privatePostPrivateCancelOrder (params?: {}): Promise<implicitReturnType>;
    privatePostPrivateGetAccountInformation (params?: {}): Promise<implicitReturnType>;
    privatePostPrivateGetOpenOrders (params?: {}): Promise<implicitReturnType>;
    privatePostPrivateGetOrderHistory (params?: {}): Promise<implicitReturnType>;
    privatePostPrivateGetOrderDetails (params?: {}): Promise<implicitReturnType>;
    privatePostPrivateGetTradeHistory (params?: {}): Promise<implicitReturnType>;
}
abstract class Exchange extends _Exchange {}

export default Exchange