<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class osl extends \ccxt\Exchange {
    public function v3_public_get_currencystatic($params = array()) {
        return $this->request('currencyStatic', array('v3', 'public'), 'GET', $params);
    }
    public function v4_private_get_instrument($params = array()) {
        return $this->request('instrument', array('v4', 'private'), 'GET', $params);
    }
    public function v4_private_get_user_wallet($params = array()) {
        return $this->request('user/wallet', array('v4', 'private'), 'GET', $params);
    }
    public function v4_private_get_orderbook_l2($params = array()) {
        return $this->request('orderBook/L2', array('v4', 'private'), 'GET', $params);
    }
    public function v3PublicGetCurrencyStatic($params = array()) {
        return $this->request('currencyStatic', array('v3', 'public'), 'GET', $params);
    }
    public function v4PrivateGetInstrument($params = array()) {
        return $this->request('instrument', array('v4', 'private'), 'GET', $params);
    }
    public function v4PrivateGetUserWallet($params = array()) {
        return $this->request('user/wallet', array('v4', 'private'), 'GET', $params);
    }
    public function v4PrivateGetOrderBookL2($params = array()) {
        return $this->request('orderBook/L2', array('v4', 'private'), 'GET', $params);
    }
}