<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class pintu extends \ccxt\Exchange {
    public function public_get_public_get_symbols_reference($params = array()) {
        return $this->request('public/get-symbols-reference', 'public', 'GET', $params);
    }
    public function public_get_public_get_book($params = array()) {
        return $this->request('public/get-book', 'public', 'GET', $params);
    }
    public function private_post_private_place_order($params = array()) {
        return $this->request('private/place-order', 'private', 'POST', $params);
    }
    public function private_post_private_cancel_order($params = array()) {
        return $this->request('private/cancel-order', 'private', 'POST', $params);
    }
    public function private_post_private_get_account_information($params = array()) {
        return $this->request('private/get-account-information', 'private', 'POST', $params);
    }
    public function private_post_private_get_open_orders($params = array()) {
        return $this->request('private/get-open-orders', 'private', 'POST', $params);
    }
    public function private_post_private_get_order_history($params = array()) {
        return $this->request('private/get-order-history', 'private', 'POST', $params);
    }
    public function private_post_private_get_order_details($params = array()) {
        return $this->request('private/get-order-details', 'private', 'POST', $params);
    }
    public function private_post_private_get_trade_history($params = array()) {
        return $this->request('private/get-trade-history', 'private', 'POST', $params);
    }
    public function publicGetPublicGetSymbolsReference($params = array()) {
        return $this->request('public/get-symbols-reference', 'public', 'GET', $params);
    }
    public function publicGetPublicGetBook($params = array()) {
        return $this->request('public/get-book', 'public', 'GET', $params);
    }
    public function privatePostPrivatePlaceOrder($params = array()) {
        return $this->request('private/place-order', 'private', 'POST', $params);
    }
    public function privatePostPrivateCancelOrder($params = array()) {
        return $this->request('private/cancel-order', 'private', 'POST', $params);
    }
    public function privatePostPrivateGetAccountInformation($params = array()) {
        return $this->request('private/get-account-information', 'private', 'POST', $params);
    }
    public function privatePostPrivateGetOpenOrders($params = array()) {
        return $this->request('private/get-open-orders', 'private', 'POST', $params);
    }
    public function privatePostPrivateGetOrderHistory($params = array()) {
        return $this->request('private/get-order-history', 'private', 'POST', $params);
    }
    public function privatePostPrivateGetOrderDetails($params = array()) {
        return $this->request('private/get-order-details', 'private', 'POST', $params);
    }
    public function privatePostPrivateGetTradeHistory($params = array()) {
        return $this->request('private/get-trade-history', 'private', 'POST', $params);
    }
}